### ISSUE TITLE
在linux下复现代码

### ISSUE THREAD

**Issue by hzyBupt** [alexxu1988/ADJSCC#6]
作者你好，我正在尝试在linux下复现项目，但是项目中的[libtensorflow_compression.so]文件是MacOS的接口？运行后显示：tensorflow.python.framework.errors_impl.NotFoundError: /root/ADJSCC-main/tensorflow_compression/python/ops/../../cc/libtensorflow_compression.so: invalid ELF header
我无法在linux下使用。我尝试自己生成一个so文件，但一直失败。请问是否有什么办法可以让我能够在linux下运行呢？(https://github.com/alexxu1988/ADJSCC/blob/main/tensorflow_compression/cc/libtensorflow_compression.so)
下面是我运行时的报错信息：

root@d8bfc2d8bbf3:~/ADJSCC-main# /bin/python3.8 /root/ADJSCC-main/adjscc_cifar10.py
2023-06-07 09:30:12.700859: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/root/ADJSCC-main/adjscc_cifar10.py", line 2, in <module>
    from util_module import Attention_Encoder, Attention_Decoder
  File "/root/ADJSCC-main/util_module.py", line 1, in <module>
    import tensorflow_compression as tfc
  File "/root/ADJSCC-main/tensorflow_compression/__init__.py", line 30, in <module>
    from tensorflow_compression.python.entropy_models.continuous_batched import *
  File "/root/ADJSCC-main/tensorflow_compression/python/entropy_models/continuous_batched.py", line 20, in <module>
    from tensorflow_compression.python.entropy_models import continuous_base
  File "/root/ADJSCC-main/tensorflow_compression/python/entropy_models/continuous_base.py", line 24, in <module>
    from tensorflow_compression.python.ops import range_coding_ops
  File "/root/ADJSCC-main/tensorflow_compression/python/ops/range_coding_ops.py", line 26, in <module>
    ops = namespace_helper.get_ops(load_library.load_op_library(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/load_library.py", line 54, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /root/ADJSCC-main/tensorflow_compression/python/ops/../../cc/libtensorflow_compression.so: invalid ELF header

**Comment by JustLiu223** [comment]
请问解决了吗，我也遇到了同样的问题

**Comment by hzyBupt** [comment]
> 请问解决了吗，我也遇到了同样的问题

 我有点忘记了。但是我应该是从tensorflow的compression那个仓库复制了对应的文件夹放在项目文件下，然后就跑通了。但是我后面是用的docker环境跑的

**Comment by JustLiu223** [comment]
好的好的，太感谢了，我去试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月4日(周一) 晚上10:06
收件人: ***@***.***&gt;;
抄送: "Just ***@***.******@***.***&gt;;
主题: Re: [alexxu1988/ADJSCC] 在linux下复现代码 (Issue #6)




  
请问解决了吗，我也遇到了同样的问题
  
我有点忘记了。但是我应该是从tensorflow的compression那个仓库复制了对应的文件夹放在项目文件下，然后就跑通了。但是我后面是用的docker环境跑的

**Comment by 0r4ngee** [comment]
> 好的好的，太感谢了，我去试试
> […](#)

请问你解决了吗？我也遇到了这个问题
